export const DashboardTenderModel = {
  result_id: 0,
  search_text: "",
  contract_date_from: "",
  contract_date_to: "",
  publication_date_from: "",
  publication_date_to: "",
  state_ids: "",
  city_ids: "",
  keyword_ids: "",
  organization_id: 0,
  organization_type_name: "",
  tender_value_operator: 0,
  contract_value_operator: 0,
  contract_value_from: 0,
  contract_value_to: 0,
  tender_value_from: 0,
  tender_value_to: 0,
  participant_name: "",
  winner_bidder: "",
  stage: "",
  sort_by: 0,
  sort_type: 0,
  page_no: 1,
  record_per_page: 5,
  bidder_name: localStorage.getItem("user_name"),
  tender_status: 0,
};

// participant_name and stage manipulating this data in future...... as per requirements
